### ISSUE TITLE
Data hardcoded in the code

### ISSUE THREAD

**Issue by cybercamphackathon** [MEFS2019/ESWifi#9]
This probably shouldn't be hardcoded in the code:
https://github.com/MEFS2019/ESWifi/blob/master/src/pages/CheckNetwork.js#L19

**Comment by SantiEspada** [comment]
Thanks for having the time to review our code. In this case, I don't think this is a problem as those are not really credentials or secrets of the app itself, they're just a fallback in case the currently selected router configuration does not provide any known default credentials. Anyway, if you still think it should be extracted anywhere else we will consider it once we have finished the core functionality and get some time to do a bit of housekeeping.
